class Facilitation {
  bool refrigerator,
      hairDryer,
      telephone,
      safeBox,
      oven,
      television,
      microwave,
      coffeeMaker,
      airConditioner,
      hotWater,
      furniture,
      cookingBasics,
      wifi,
      parking,
      bathroomEssentials,
      dishWasher,
      washingMachine;

  Facilitation(
      {this.refrigerator,
      this.hairDryer,
      this.telephone,
      this.safeBox,
      this.oven,
      this.television,
      this.microwave,
      this.coffeeMaker,
      this.hotWater,
      this.furniture,
      this.airConditioner,
      this.dishWasher,
      this.bathroomEssentials,
      this.cookingBasics,
      this.parking,
      this.wifi,
      this.washingMachine});
}
